name: SAST - Semgrep

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: #allows manual trigger from GitHub UI

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep and Generate JSON Report
        run: |
          mkdir -p reports
          semgrep scan \
            --config p/owasp-top-ten \
            --config p/secrets \
            --config p/nodejs \
            --severity WARNING \
            --severity ERROR \
            --json \
            --output reports/semgrep.json
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} # optional, works without it
        continue-on-error: true # Ensures pipeline passes even if findings exist, allowing manual triage

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: reports/semgrep.json
          retention-days: 30
