name: SAST - Semgrep

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: #allows manual trigger from GitHub UI

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep (OWASP Top 10 + Secrets)
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            p/owasp-top-ten
            p/secrets
            p/nodejs
          generateSarif: false 
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} # optional, works without it

      # Run again with JSON output for our aggregator
      - name: Run Semgrep (JSON output for aggregator)
        run: |
          pip install semgrep
          semgrep \
            --config p/owasp-top-ten \
            --config p/secrets \
            --config p/nodejs \
            --json \
            --ouput reports/semgrep.json \
            --severity WARNING \
            --severity ERROR \
            . || true  # don't fail the pipeline on findings — we triage ourselves

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: reports/semgrep.json
          retention-days: 30
